root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "templ"]
  exclude_dir = ["bin", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test\\.go", "_templ\\.go"]
  delay = 500
  kill_delay = "2s"
  rerun = false

[log]
  time = false

[screen]
  clear_on_rebuild = false
