// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ntentasd/meridian/internal/store"

func Index(entries []store.RouteEntry) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Meridian</title><script src=\"https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js\"></script><script src=\"https://unpkg.com/htmx-ext-sse@2.2.2/sse.js\"></script><style>\n\t\t\t\t*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n\t\t\t\tbody { font-family: ui-monospace, monospace; background: #0d1117; color: #e6edf3; padding: 2rem; }\n\t\t\t\th1 { font-size: 1.25rem; font-weight: 600; margin-bottom: 1.5rem; color: #58a6ff; }\n\t\t\t\ttable { width: 100%; border-collapse: collapse; font-size: 0.875rem; }\n\t\t\t\tthead th { padding: 0.5rem 1rem; text-align: left; color: #8b949e; border-bottom: 1px solid #21262d; font-weight: 500; }\n\t\t\t\ttbody tr { border-bottom: 1px solid #161b22; transition: background 0.1s; }\n\t\t\t\ttbody tr:hover { background: #161b22; }\n\t\t\t\ttd { padding: 0.6rem 1rem; }\n\t\t\t\t.kind-ingress { color: #79c0ff; }\n\t\t\t\t.kind-httproute { color: #7ee787; }\n\t\t\t\t.empty { padding: 2rem 1rem; color: #8b949e; text-align: center; }\n\t\t\t\ta { color: #58a6ff; text-decoration: none; }\n\t\t\t\ta:hover { text-decoration: underline; }\n\t\t\t</style></head><body><h1>Meridian</h1><table><thead><tr><th>Name</th><th>Namespace</th><th>Kind</th><th>Hostnames</th><th>Owner</th></tr></thead> <tbody id=\"routes\" hx-ext=\"sse\" sse-connect=\"/ui/events\" sse-swap=\"update\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(entries) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<tr><td colspan=\"5\" class=\"empty\">No routes discovered yet.</td></tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			for _, e := range entries {
				templ_7745c5c3_Err = Row(e).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</tbody></table></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
